-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND CONFIG — split into modules in this directory. --
-- Edit the individual *.lua files; this file just loads   --
-- them. See https://wiki.hypr.land/Configuring/Start/      --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

require("monitors")        -- monitor layout
require("programs")        -- shared program names (returns a table)
require("environment")     -- environment variables
require("permissions")     -- (commented) permission rules
require("look-and-feel")   -- general, decoration, animations
require("layouts")         -- dwindle / master / scrolling
require("misc")            -- misc tweaks
require("input")           -- keyboard, touchpad, gestures, devices
require("keybindings")     -- key/mouse binds
require("window-rules")    -- window & layer rules
require("autostart")       -- processes started with Hyprland
